kind: pipeline
type: docker
name: default

services:
  - name: database
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: password

steps:
  - name: test
    image: ubuntu:20.04
    environment:
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: password
    commands:
      - apt update && DEBIAN_FRONTEND=noninteractive apt install -y libssl-dev build-essential liboctave-dev octave libmariadb-dev libmariadbclient-dev libmariadb3 build-essential curl
      - make build
      - curl https://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m > mUnittest.m
      - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'



