pipeline:
  test:
    image: alpine:edge
    environment:
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD=password
    commands:
      - apk --update --no-cache add mariadb-client mariadb-dev alpine-sdk curl
      - echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
      - apk --update --no-cache add octave
      - apk --update --no-cache add mariadb-client mariadb-dev
      - make mysql
      - curl https://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m > mUnittest.m
      - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

services:
  database:
    image: mariadb:10.4.12
    environment:
      - MYSQL_ROOT_PASSWORD=password

