image: registry.gitlab.com/markuman/dev/octave:4.2.0

variables:
  DOCKER_DRIVER: overlay
  MYSQL_ROOT_PASSWORD: password
  MYSQL_HOST: mariadb

stages:
  - build
  - test

mariadb 10.2 alpine:
  stage: build
  tags:
    - docker
    - shared
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev
    - make mysql

    
mariadb 5.5 centos:
  image: centos:7
  stage: build
  tags:
    - docker
    - shared
  script:
    - yum install -y epel-release
    - yum install -y mariadb-libs mariadb-devel make gcc octave-devel
    - make centos

mariadb 10.2:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: mariadb:10.2.15
      alias: mariadb
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev
    - wget http://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m
    - make mysql
    - md5sum mUnittest.m
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

mariadb 10.3:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: mariadb:10.3.10
      alias: mariadb
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev
    - wget http://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m
    - make mysql
    - md5sum mUnittest.m
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

mariadb 10.1:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: mariadb:10.1.35
      alias: mariadb
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev
    - wget http://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m
    - make mysql
    - md5sum mUnittest.m
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

mariadb 10.0:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: mariadb:10.0.36
      alias: mariadb
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev
    - wget http://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m
    - make mysql
    - md5sum mUnittest.m
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

mariadb 5.5:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: mariadb:5.5.61
      alias: mariadb
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev
    - wget http://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m
    - make mysql
    - md5sum mUnittest.m
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

mysql 5.7:
  stage: test
  tags:
    - docker
    - shared
  services:
    - name: mysql:5.7.21
      alias: mariadb
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev
    - wget http://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m
    - make mysql
    - octave-cli --eval 'quit(or(0, mUnittest("gitlabci")))'

