include:
  - '/gitlabci/build.yml'
  - '/gitlabci/test.yml'

image: alpine:edge

variables:
  DOCKER_DRIVER: overlay
  MYSQL_ROOT_PASSWORD: password
  MYSQL_HOST: mariadb

stages:
  - build
  - test

before_script:
  - apk --update --no-cache add mariadb-client mariadb-dev alpine-sdk curl && echo "done" || yum install -y epel-release
  - echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
  - apk --update --no-cache add octave && echo "done" || yum install -y curl mariadb-libs mariadb-devel make gcc octave-devel
  - curl http://git.osuv.de/m/mUnittest/raw/branch/master/mUnittest.m > mUnittest.m
