include:
  - '/gitlabci/build.yml'
  - '/gitlabci/test.yml'

image: registry.gitlab.com/markuman/dev/octave:4.2.0

variables:
  DOCKER_DRIVER: overlay
  MYSQL_ROOT_PASSWORD: password
  MYSQL_HOST: mariadb

stages:
  - build
  - test
