mariadb 10.3 alpine:
  image: alpine:edge
  stage: build
  tags:
    - docker
    - shared
  script:
    - make mysql

    
mariadb 5.5 centos:
  image: centos:7
  stage: build
  tags:
    - docker
    - shared
  script:
    - yum install -y epel-release
    - yum install -y mariadb-libs mariadb-devel make gcc octave-devel
    - make centos
