mariadb 10.3 alpine:
  image: alpine:edge
  stage: build
  tags:
    - docker
    - shared
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev alpine-sdk
    - echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
    - apk --update --no-cache add octave
    - make mysql

    
mariadb 5.5 centos:
  image: centos:7
  stage: build
  tags:
    - docker
    - shared
  script:
    - yum install -y epel-release
    - yum install -y mariadb-libs mariadb-devel make gcc octave-devel
    - make centos
