mariadb 10.3 alpine:
  image: alpine:edge
  stage: build
  tags:
    - docker
    - shared
  script:
    - apk --update --no-cache add mariadb-client mariadb-dev alpine-sdk curl
    - echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
    - apk --update --no-cache add octave
    - make mysql

mariadb 5.5 centos:
  image: centos:7
  stage: build
  tags:
    - docker
    - shared
  script:
    - yum install -y epel-release
    - yum install -y mariadb-libs mariadb-devel make gcc octave-devel
    - make centos

octave 4.4.1:
  image: mtmiller/octave:4.4.1
  stage: build
  tags:
    - docker
    - shared
  script:
    - apt update && apt install libmysqlclient-dev libssl-dev -y
    - make mysql

octave 5.1.0:
  image: mtmiller/octave:5.1.0
  stage: build
  tags:
    - docker
    - shared
  script:
    - apt update && apt install libmysqlclient-dev libssl-dev -y
    - make mysql

octave 6.0.0:
  image: mtmiller/octave:6.0.0
  stage: build
  tags:
    - docker
    - shared
  script:
    - apt update && apt install libmysqlclient-dev libssl-dev -y
    - make mysql
